# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
FROM {{BASE_IMAGE}}
RUN apt-get update && apt-get install -y --no-install-recommends bats && rm -rf /var/lib/apt/lists/*
COPY --chmod=755 run-bats.bash /usr/local/bin/run-bats
